name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: football_manager_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "football-manager-backend/yarn.lock"

      - name: Install dependencies
        working-directory: football-manager-backend
        run: yarn install --frozen-lockfile

      - name: Generate Prisma client
        working-directory: football-manager-backend
        run: yarn prisma:generate

      - name: Run tests
        working-directory: football-manager-backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/football_manager_test
          JWT_SECRET: test-jwt-secret
        run: yarn test

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "football-manager-frontend/yarn.lock"

      - name: Install dependencies
        working-directory: football-manager-frontend
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: football-manager-frontend
        run: yarn test
